export const enderecosData = [
  {
    id: 0,
    logradouro: "Rua das Flores",
    numero: "123",
    cidade: "Porto Alegre",
    uf: "RS",
    cep: "90000-000",
    isFavorited: false,
  },
  {
    id: 1,
    logradouro: "Avenida Brasil",
    numero: "456",
    cidade: "São Paulo",
    uf: "SP",
    cep: "01000-000",
    isFavorited: false,
  },
  {
    id: 2,
    logradouro: "Rua 7 de Setembro",
    numero: "789",
    cidade: "Rio de Janeiro",
    uf: "RJ",
    cep: "20000-000",
    isFavorited: false,
  },
  {
    id: 3,
    logradouro: "Rua da Harmonia",
    numero: "101",
    cidade: "Curitiba",
    uf: "PR",
    cep: "80000-000",
    isFavorited: false,
  },
  {
    id: 4,
    logradouro: "Avenida Independência",
    numero: "202",
    cidade: "Salvador",
    uf: "BA",
    cep: "40000-000",
    isFavorited: false,
  },
  {
    id: 5,
    logradouro: "Rua Augusta",
    numero: "303",
    cidade: "São Paulo",
    uf: "SP",
    cep: "01300-000",
    isFavorited: false,
  },
  {
    id: 6,
    logradouro: "Rua Sete de Abril",
    numero: "404",
    cidade: "Rio de Janeiro",
    uf: "RJ",
    cep: "20050-000",
    isFavorited: false,
  },
  {
    id: 7,
    logradouro: "Rua XV de Novembro",
    numero: "505",
    cidade: "Florianópolis",
    uf: "SC",
    cep: "88000-000",
    isFavorited: false,
  },
  {
    id: 8,
    logradouro: "Avenida Goiás",
    numero: "606",
    cidade: "Goiânia",
    uf: "GO",
    cep: "74000-000",
    isFavorited: false,
  },
  {
    id: 9,
    logradouro: "Rua das Palmeiras",
    numero: "707",
    cidade: "Belo Horizonte",
    uf: "MG",
    cep: "30000-000",
    isFavorited: false,
  },
]
