export const lojasData = [
  {
    id: 0,
    nome: "Lanches da Deusa",
    desconto: "Até 50% OFF",
    avaliacao: "5,0",
    categoria: "Lancheria",
    horario: "10:00 às 22:00",
    distancia: "1,2 Km",
    isFavorited: false,
    imagePath: "/src/ui/assets/image.png",
    logoPath: "/src/ui/assets/image2.png",
  },
  {
    id: 1,
    nome: "Dragão Verde",
    desconto: "20% OFF",
    avaliacao: "4,7",
    categoria: "Lancheria",
    horario: "11:00 às 23:00",
    distancia: "3,4 Km",
    isFavorited: false,
    imagePath: "/src/ui/assets/dragao_verde_img.png",
    logoPath: "/src/ui/assets/dragao_verde_logo.png"
  },
  {
    id: 2,
    nome: "Artesanto do Pastel",
    desconto: "Compre 1, leve 2",
    avaliacao: "4,9",
    categoria: "Pastelaria",
    horario: "08:00 às 14:00",
    distancia: "2,1 Km",
    isFavorited: false,
    imagePath: "/src/ui/assets/artesanato_pastel_img.png",
    logoPath: "/src/ui/assets/artesanato_pastel_logo.png"
  },
  {
    id: 3,
    nome: "Doce Encanto",
    desconto: "Até 30% OFF",
    avaliacao: "4,8",
    categoria: "Confeitaria",
    horario: "09:00 às 20:00",
    distancia: "2,8 Km",
    isFavorited: false,
    imagePath: "/path/to/loja4-image.png",
    logoPath: "/path/to/loja4-logo.png",
  },
  {
    id: 4,
    nome: "Bistrô Gourmet",
    desconto: "10% OFF",
    avaliacao: "4,6",
    categoria: "Restaurante",
    horario: "12:00 às 23:00",
    distancia: "4,0 Km",
    isFavorited: false,
    imagePath: "/path/to/loja5-image.png",
    logoPath: "/path/to/loja5-logo.png",
  },
  {
    id: 5,
    nome: "Sabores do Mundo",
    desconto: "15% OFF",
    avaliacao: "4,5",
    categoria: "Restaurante Internacional",
    horario: "13:00 às 22:00",
    distancia: "3,2 Km",
    isFavorited: false,
    imagePath: "/path/to/loja6-image.png",
    logoPath: "/path/to/loja6-logo.png",
  },
  {
    id: 6,
    nome: "Sabores do Mundo",
    desconto: "15% OFF",
    avaliacao: "4,5",
    categoria: "Restaurante Internacional",
    horario: "13:00 às 22:00",
    distancia: "3,2 Km",
    isFavorited: false,
    imagePath: "/path/to/loja6-image.png",
    logoPath: "/path/to/loja6-logo.png",
  },
  {
    id: 7,
    nome: "Frutos do Mar",
    desconto: "Até 25% OFF",
    avaliacao: "4,9",
    categoria: "Peixaria",
    horario: "10:00 às 21:00",
    distancia: "2,5 Km",
    isFavorited: false,
    imagePath: "/path/to/loja7-image.png",
    logoPath: "/path/to/loja7-logo.png",
  },
  {
    id: 8,
    nome: "Churrascaria do Chef",
    desconto: "20% OFF",
    avaliacao: "4,7",
    categoria: "Churrascaria",
    horario: "11:00 às 23:00",
    distancia: "3,4 Km",
    isFavorited: false,
    imagePath: "/path/to/loja8-image.png",
    logoPath: "/path/to/loja8-logo.png",
  },
  {
    id: 9,
    nome: "Panificadora Pão Quente",
    desconto: "Compre 1, leve 2",
    avaliacao: "4,9",
    categoria: "Panificadora",
    horario: "06:00 às 20:00",
    distancia: "2,1 Km",
    isFavorited: false,
    imagePath: "/path/to/loja9-image.png",
    logoPath: "/path/to/loja9-logo.png",
  },
  {
    id: 10,
    nome: "Empório Gourmet",
    desconto: "Até 50% OFF",
    avaliacao: "5,0",
    categoria: "Empório",
    horario: "10:00 às 22:00",
    distancia: "1,2 Km",
    isFavorited: false,
    imagePath: "/path/to/loja10-image.png",
    logoPath: "/path/to/loja10-logo.png",
  },
  {
    id: 11,
    nome: "Sushi House",
    desconto: "20% OFF",
    avaliacao: "4,7",
    categoria: "Sushi Bar",
    horario: "11:00 às 23:00",
    distancia: "3,4 Km",
    isFavorited: false,
    imagePath: "/path/to/loja11-image.png",
    logoPath: "/path/to/loja11-logo.png",
  },
  {
    id: 12,
    nome: "Café Colonial",
    desconto: "Compre 1, leve 2",
    avaliacao: "4,9",
    categoria: "Cafeteria",
    horario: "08:00 às 14:00",
    distancia: "2,1 Km",
    isFavorited: false,
    imagePath: "/path/to/loja12-image.png",
    logoPath: "/path/to/loja12-logo.png",
  },
];
