export const productList = [
  {
    id: 0,
    foto: "/path/to/banana.jpg",
    name: "Banana",
    description: "Banana .......",
    expirationDate: "10/10/2025",
    quantity: 10,
    originalPrice: 10,
    sellPrice: 5,
    status: true,
  },
  {
    id: 1,
    foto: "/path/to/apple.jpg",
    name: "Apple",
    description: "Fresh Apple",
    expirationDate: "12/10/2022",
    quantity: 15,
    originalPrice: 20,
    sellPrice: 10,
    status: true,
  },

  {
    id: 3,
    foto: "/path/to/grape.jpg",
    name: "Grape",
    description: "Sweet Grape",
    expirationDate: "10/15/2024",
    quantity: 12,
    originalPrice: 15,
    sellPrice: 8,
    status: true,
  },
  {
    id: 4,
    foto: "/path/to/watermelon.jpg",
    name: "Watermelon",
    description: "Juicy Watermelon",
    expirationDate: "02/20/2024",
    quantity: 10,
    originalPrice: 18,
    sellPrice: 9,
    status: false,
  },
  {
    id: 5,
    foto: "/path/to/strawberry.jpg",
    name: "Strawberry",
    description: "Sweet Strawberry",
    expirationDate: "01/22/2024",
    quantity: 15,
    originalPrice: 20,
    sellPrice: 10,
    status: true,
  },
]
